In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Working with text 
## exercise from lecture

In [3]:
eu_restaurants = pd.read_csv("data/European Restaurant Reviews.csv" , header = None)
eu_restaurants.columns = ["Country", "Restaurant Name", "Sentiment", "Review Title", "Review Date", "Review"] 
eu_restaurants

,Country,Restaurant Name,Sentiment,Review Title,Review Date,Review
0,Country,Restaurant Name,Sentiment,Review Title,Review Date,Review
1,France,The Frog at Bercy Village,Negative,Rude manager,May 2024 •,The manager became agressive when I said the c...
2,France,The Frog at Bercy Village,Negative,A big disappointment,Feb 2024 •,"I ordered a beef fillet ask to be done medium,..."
3,France,The Frog at Bercy Village,Negative,Pretty Place with Bland Food,Nov 2023 •,"This is an attractive venue with welcoming, al..."
4,France,The Frog at Bercy Village,Negative,Great service and wine but inedible food,Mar 2023 •,Sadly I used the high TripAdvisor rating too ...
...,...,...,...,...,...,...
1498,Cuba,Old Square (Plaza Vieja),Negative,The Tourism Trap,Oct 2016 •,Despite the other reviews saying that this is ...
1499,Cuba,Old Square (Plaza Vieja),Negative,the beer factory,Oct 2016 •,beer is good. food is awfull The only decent...
1500,Cuba,Old Square (Plaza Vieja),Negative,brewery,Oct 2016 •,"for terrible service of a truly comedic level,..."
1501,Cuba,Old Square (Plaza Vieja),Negative,It's nothing exciting over there,Oct 2016 •,We visited the Havana's Club Museum which is l...
1502,Cuba,Old Square (Plaza Vieja),Negative,Tourist Trap,Oct 2016 •,Food and service was awful. Very pretty stop. ...

In [4]:
eu_restaurants.describe

<bound method NDFrame.describe of       Country            Restaurant Name  Sentiment  \
0     Country            Restaurant Name  Sentiment
1      France  The Frog at Bercy Village   Negative
2      France  The Frog at Bercy Village   Negative
3      France  The Frog at Bercy Village   Negative
4      France  The Frog at Bercy Village   Negative
...       ...                        ...        ...
1498     Cuba   Old Square (Plaza Vieja)   Negative
1499     Cuba   Old Square (Plaza Vieja)   Negative
1500     Cuba   Old Square (Plaza Vieja)   Negative
1501     Cuba   Old Square (Plaza Vieja)   Negative
1502     Cuba   Old Square (Plaza Vieja)   Negative

                                  Review Title  Review Date  \
0                                 Review Title  Review Date
1                                 Rude manager   May 2024 •
2                         A big disappointment   Feb 2024 •
3                 Pretty Place with Bland Food   Nov 2023 •
4     Great service and wine but inedible food   Mar 2023 •
...                                        ...          ...
1498                          The Tourism Trap   Oct 2016 •
1499                          the beer factory   Oct 2016 •
1500                                   brewery   Oct 2016 •
1501          It's nothing exciting over there   Oct 2016 •
1502                              Tourist Trap   Oct 2016 •

                                                 Review
0                                                Review
1     The manager became agressive when I said the c...
2     I ordered a beef fillet ask to be done medium,...
3     This is an attractive venue with welcoming, al...
4     Sadly I  used the high TripAdvisor rating too ...
...                                                 ...
1498  Despite the other reviews saying that this is ...
1499  beer is good.  food is awfull  The only decent...
1500  for terrible service of a truly comedic level,...
1501  We visited the Havana's Club Museum which is l...
1502  Food and service was awful. Very pretty stop. ...

[1503 rows x 6 columns]>

In [5]:
eu_restaurants.info

<bound method DataFrame.info of       Country            Restaurant Name  Sentiment  \
0     Country            Restaurant Name  Sentiment
1      France  The Frog at Bercy Village   Negative
2      France  The Frog at Bercy Village   Negative
3      France  The Frog at Bercy Village   Negative
4      France  The Frog at Bercy Village   Negative
...       ...                        ...        ...
1498     Cuba   Old Square (Plaza Vieja)   Negative
1499     Cuba   Old Square (Plaza Vieja)   Negative
1500     Cuba   Old Square (Plaza Vieja)   Negative
1501     Cuba   Old Square (Plaza Vieja)   Negative
1502     Cuba   Old Square (Plaza Vieja)   Negative

                                  Review Title  Review Date  \
0                                 Review Title  Review Date
1                                 Rude manager   May 2024 •
2                         A big disappointment   Feb 2024 •
3                 Pretty Place with Bland Food   Nov 2023 •
4     Great service and wine but inedible food   Mar 2023 •
...                                        ...          ...
1498                          The Tourism Trap   Oct 2016 •
1499                          the beer factory   Oct 2016 •
1500                                   brewery   Oct 2016 •
1501          It's nothing exciting over there   Oct 2016 •
1502                              Tourist Trap   Oct 2016 •

                                                 Review
0                                                Review
1     The manager became agressive when I said the c...
2     I ordered a beef fillet ask to be done medium,...
3     This is an attractive venue with welcoming, al...
4     Sadly I  used the high TripAdvisor rating too ...
...                                                 ...
1498  Despite the other reviews saying that this is ...
1499  beer is good.  food is awfull  The only decent...
1500  for terrible service of a truly comedic level,...
1501  We visited the Havana's Club Museum which is l...
1502  Food and service was awful. Very pretty stop. ...

[1503 rows x 6 columns]>

In [9]:
alice = pd.read_table("data/alice.txt", sep="\t")
alice

ParserError: Error tokenizing data. C error: Expected 1 fields in line 60, saw 2